### ISSUE TITLE
mongoose schema generator throws on null value (patch)

### ISSUE THREAD

**Issue by RockyRoad29** [nijikokun/generate-schema#20]
Hi Nijiko,

Thanks for this useful module.

I was trying it on a rather big json output from a web API, but it failed when hitting null values.

Here's a sample output 
```
> data
{ a: 1, b: 2, x: null }
> GenerateSchema.json(data)
{ '$schema': 'http://json-schema.org/draft-04/schema#',
  type: 'object',
  properties: 
   { a: { type: 'number' },
     b: { type: 'number' },
     x: { type: 'null' } } }
> GenerateSchema.mongoose(data)
TypeError: Cannot read property 'toString' of null
    at Object.Process [as mongoose] (/home/mich/.nvm/versions/node/v7.4.0/lib/node_modules/generate-schema/src/schemas/mongoose.js:49:21)
    at repl:1:16
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:544:10)
    at emitOne (events.js:101:20)
```
I'm just starting with mongoose and json schemas so I don't know yet what should be the correct behavior, but I can suggest this simple patch to fix the issue (though a bit of refactoring may be needed):

```
--- src/schemas/mongoose.js	2017-01-08 16:47:22.301455645 +0100
+++ /home/mich/.nvm/versions/node/v7.4.0/lib/node_modules/generate-schema/src/schemas/mongoose.js	2017-01-08 17:56:16.659882008 +0100
@@ -46,7 +46,7 @@ module.exports = function Process (objec
       type = 'buffer'
     }
 
-    if (typeof value.toString !== 'undefined' && value.toString().match(/^[0-9a-fA-F]{24}$/)) {
+    if (value!=null && typeof value.toString !== 'undefined' && value.toString().match(/^[0-9a-fA-F]{24}$/)) {
       type = 'objectid'
     }
```

Here's how it goes once the change applied:
```
 > var GenerateSchema = require('generate-schema');
undefined
> data = { a: 1, b: 2, x: null }
{ a: 1, b: 2, x: null }
> GenerateSchema.mongoose(data)
{ a: 'Number', b: 'Number', x: 'Mixed' }
```

**Comment by nijikokun** [comment]
Thanks for reporting, this has been addressed in `2.3.3` which has been published :+1:
